name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 开启corepack
        run: corepack enable
      - name: 安装依赖
        run: yarn install
      - name: 执行 lint 脚本
        run: yarn run lint

  linked_list:
    name: '@daifee/linked-list'
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      PACKAGE_PATH: './packages/linked-list/'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 开启corepack
        run: corepack enable
      - name: 安装依赖
        run: |
          cd $PACKAGE_PATH
          yarn install
      - name: 执行 test 脚本
        run: |
          cd $PACKAGE_PATH
          yarn test
      - uses: codecov/codecov-action@v3
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/linked-list/coverage/clover.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
