name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          # cache-dependency-path: './packages/**/yarn.lock'
      - name: 开启corepack
        run: corepack enable
      - name: 安装依赖
        run: yarn install --immutable
      - name: 执行 lint 脚本
        run: yarn run lint
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          # cache-dependency-path: './packages/**/yarn.lock'
      - name: 开启corepack
        run: corepack enable
      - name: 初始化项目
        run: |
          yarn install --immutable
          yarn run bootstrap
      - name: 执行 test 脚本
        run: yarn run test
      # - name: 测试覆盖率文件
      #   id: coverage_files
      #   run: |
      #     files=$(ls packages/*/coverage/clover.xml -m)
      #     echo "value=${files}" >> $GITHUB_OUTPUT
      - name: 上传Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # files: ${{ steps.coverage_files.outputs.value }}
          files: "packages/*/coverage/clover.xml"
          flags: unittests
          fail_ci_if_error: true
          verbose: true
      

