name: 集成

on: [push, pull_request]

jobs:
  test:
    name: 测试代码
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 开启corepack功能
        run: corepack enable
      - name: 项目
        run: |
          yarn install
          yarn run lint
      - name: 包 @daifee/linked-list
        run: |
          cd packages/linked-list
          yarn install
          yarn run test
