name: lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 开启corepack
        run: corepack enable
      - name: 安装依赖
        run: yarn install
      - name: 执行检测脚本
        run: yarn run lint